apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: minqxd50u-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: minqxd50u-nodejs 
  name: minqxd50u-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: minqxd50u-nodejs 
